apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
      - image: ghcr.io/alonso-jane/2048:04fba483b5de2701222a6726f399c87bc6e9d881
        name: app-2048
        ports:
        - containerPort: 80